apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrerts
  namespace: chat-app
type: Opaque
data:
  jwt: eUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpJVXpJMU5pSjkuZXlKcGMzTWlPaUpQYm14cGJtVWdTbGRVSUVKMWFXeGtaWElpTENKcFlYUWlPakUzTXpJME5qQTFOVEVzSW1WNGNDSTZNVGMyTXprNU5qVTFNU3dpWVhWa0lqb2lkM2QzTG1WNFlXMXdiR1V1WTI5dElpd2ljM1ZpSWpvaWFuSnZZMnRsZEVCbGVHRnRjR3hsTG1OdmJTSXNJa2RwZG1WdVRtRnRaU0k2SWtwdmFHNXVlU0lzSWxOMWNtNWhiV1VpT2lKU2IyTnJaWFFpTENKRmJXRnBiQ0k2SW1weWIyTnJaWFJBWlhoaGJYQnNaUzVqYjIwaUxDSlNiMnhsSWpwYklrMWhibUZuWlhJaUxDSlFjbTlxWldOMElFRmtiV2x1YVhOMGNtRjBiM0lpWFgwLllUZVI2ekxDS3VPUGp6NUNZZnd4VzFnWHBfd1AxZ0FuTjNxU01KSUZRRmc=
